[project]
name = "mcp-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.14.1",
    "minsearch>=0.0.7",
    "requests>=2.32.5",
    "whoosh>=2.7.4",
]
